### ISSUE TITLE
Messenger Left Sidebar Hider

### ISSUE THREAD

**Issue by wolfgrrl** [Gersonzao/USERCSS#1]
**Describe the bug**
Left Sidebar is not hidden

**Software version**
Chrome Version 108.0.5359.125 (Official Build) (64-bit)
Stylus version: 1.5.28

Just installed this today and the left sidebar is not hidden. Can you please assist? Thank you!

**Comment by Gersonzao** [comment]
Hello, thanks for reporting the bug! This should have been fixed, please update the style. It looks like the sidebar didn't get hidden when it wasn't in the compact state. More info: https://github.com/Gersonzao/userCSS/commit/14e6490136fd39e73370f0eb108d5326c52d7987

**Comment by Gersonzao** [comment]
Reminder that this should have been fixed.

**Comment by wolfgrrl** [comment]
Thank you!
